management:
  port: 8081
  address: 127.0.0.1
  security:
     enabled: false
  trace:
     include: REQUEST_HEADERS,RESPONSE_HEADERS,PARAMETERS,QUERY_STRING,ERRORS,PATH_INFO,PATH_TRANSLATED,CONTEXT_PATH,USER_PRINCIPAL,PARAMETERS,QUERY_STRING,AUTH_TYPE,REMOTE_ADDRESS,SESSION_ID,REMOTE_USER